"""A-vs-B agreement: how reliable are the machine labels, really?

This is the number that bounds every downstream claim about the golden set. If two
independent passes only agree at kappa 0.5 on intent, then "macro-F1 0.7" means the
classifier matched a label that a second competent labeller would have disputed a third
of the time -- and the report has to say so.

Writes the stats into golden/SAMPLING_NOTE.md (regenerating the block between markers)
so the note can never drift from the measurement.
"""
from __future__ import annotations

import json
import sys
from collections import Counter

sys.path.insert(0, ".")
from eval.metrics import cohens_kappa  # noqa: E402
from src.support_agent import config  # noqa: E402

GOLDEN = config.GOLDEN
START = "<!-- AGREEMENT:START -->"
END = "<!-- AGREEMENT:END -->"


def load(stage: str) -> list:
    p = GOLDEN / f"prelabel_{stage}.jsonl"
    if not p.exists():
        raise SystemExit(f"missing {p} -- run scripts/prelabel.py --stage {stage}")
    return [json.loads(l) for l in p.open(encoding="utf-8")]


def main() -> None:
    A, B = load("A"), load("B")
    assert len(A) == len(B), "passes have different lengths"
    ids_a = [r["id"] for r in A]
    ids_b = [r["id"] for r in B]
    assert ids_a == ids_b, "passes are not aligned by id"

    ia, ib = [r["intent"] for r in A], [r["intent"] for r in B]
    ea, eb = [bool(r["escalate"]) for r in A], [bool(r["escalate"]) for r in B]

    k_intent = cohens_kappa(ia, ib)
    k_esc = cohens_kappa([str(x) for x in ea], [str(x) for x in eb])
    agree_intent = sum(1 for x, y in zip(ia, ib) if x == y) / len(A)
    agree_esc = sum(1 for x, y in zip(ea, eb) if x == y) / len(A)

    disagreements = [i for i in range(len(A)) if ia[i] != ib[i] or ea[i] != eb[i]]
    confusions = Counter((x, y) for x, y in zip(ia, ib) if x != y)

    stats = {
        "n": len(A),
        "model_A": A[0]["labeler"], "model_B": B[0]["labeler"],
        "intent": {"raw_agreement": round(agree_intent, 4), "cohens_kappa": round(k_intent, 4)},
        "escalate": {"raw_agreement": round(agree_esc, 4), "cohens_kappa": round(k_esc, 4)},
        "n_disagreements": len(disagreements),
        "disagreement_rate": round(len(disagreements) / len(A), 4),
        "escalate_rate_A": round(sum(ea) / len(A), 4),
        "escalate_rate_B": round(sum(eb) / len(B), 4),
        "parse_failures_A": sum(1 for r in A if r.get("parse_failed")),
        "parse_failures_B": sum(1 for r in B if r.get("parse_failed")),
        "top_intent_confusions": [{"A": a, "B": b, "n": n} for (a, b), n in confusions.most_common(8)],
    }
    (GOLDEN / "ab_agreement.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(json.dumps(stats, indent=2))

    # ---- build the human review queue: ALL disagreements + a random 20% of agreements
    import random

    rng = random.Random(config.RANDOM_STATE)
    agreements = [i for i in range(len(A)) if i not in set(disagreements)]
    sampled_agree = rng.sample(agreements, max(1, int(round(0.20 * len(agreements)))))
    queue_idx = sorted(set(disagreements) | set(sampled_agree))

    with (GOLDEN / "review_queue.jsonl").open("w", encoding="utf-8") as f:
        for i in queue_idx:
            f.write(json.dumps({
                "id": A[i]["id"], "text": A[i]["text"],
                "thread_context": A[i]["thread_context"],
                "reason": "disagreement" if i in set(disagreements) else "random_audit",
                "A": {k: A[i][k] for k in ("intent", "escalate", "escalate_reason_code",
                                           "reply_must_include", "reply_must_not_include",
                                           "difficulty", "notes")},
                "B": {k: B[i][k] for k in ("intent", "escalate", "escalate_reason_code",
                                           "reply_must_include", "reply_must_not_include",
                                           "difficulty", "notes")},
            }, ensure_ascii=False) + "\n")
    print(f"\nreview queue: {len(queue_idx)} items "
          f"({len(disagreements)} disagreements + {len(sampled_agree)} random audits)")
    _update_note(stats, len(queue_idx), len(disagreements), len(sampled_agree))


def _update_note(stats: dict, q: int, d: int, a: int) -> None:
    p = GOLDEN / "SAMPLING_NOTE.md"
    block = f"""{START}
<!-- generated by scripts/ab_agreement.py -- do not edit by hand -->

| | intent | escalate |
|---|---|---|
| raw agreement | {stats['intent']['raw_agreement']:.1%} | {stats['escalate']['raw_agreement']:.1%} |
| Cohen's kappa | **{stats['intent']['cohens_kappa']:.3f}** | **{stats['escalate']['cohens_kappa']:.3f}** |

- n = {stats['n']}; Pass A = `{stats['model_A']}`, Pass B = `{stats['model_B']}`
- items where A and B disagree on intent or escalation: **{stats['n_disagreements']}** ({stats['disagreement_rate']:.1%})
- escalation rate: A {stats['escalate_rate_A']:.1%} vs B {stats['escalate_rate_B']:.1%}
- JSON parse failures: A {stats['parse_failures_A']}, B {stats['parse_failures_B']}
- **human review queue: {q} items** = {d} disagreements + {a} randomly audited agreements

Most confused intent pairs (A -> B):

| A said | B said | n |
|---|---|---|
""" + "\n".join(f"| `{c['A']}` | `{c['B']}` | {c['n']} |" for c in stats["top_intent_confusions"]) + f"""
{END}"""

    if p.exists():
        text = p.read_text(encoding="utf-8")
        if START in text and END in text:
            pre, rest = text.split(START, 1)
            _, post = rest.split(END, 1)
            p.write_text(pre + block + post, encoding="utf-8")
        else:
            p.write_text(text + "\n\n" + block + "\n", encoding="utf-8")
    else:
        p.write_text(block + "\n", encoding="utf-8")
    print(f"updated {p}")


if __name__ == "__main__":
    main()
